### ISSUE TITLE
Upgrade to .NET Core 6 or higher to publish as a single file

### ISSUE THREAD

**Issue by lonelyicer** [DangerKiddy/Headset-Battery-Info#3]
Bundling all application-dependent files into a single binary
In .NET 6, you can [publish trimmed](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-self-contained) to reduce the total size of trim-compatible applications. The single file deployment option can be combined with [ReadyToRun](https://learn.microsoft.com/en-us/dotnet/core/deploying/ready-to-run) and [Trim](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-self-contained) publish options.

**Comment by DangerKiddy** [comment]
Hey, thank you, I'll take a look later today or tomorrow!
However, I think I'll keep sound file as separate file so it can be customised

**Comment by DangerKiddy** [comment]
Yup, now it looks a lot better, thank you again, I'll publish it soon
![image](https://github.com/DangerKiddy/Headset-Battery-Info/assets/42438297/9d975a4c-fa90-477f-98a8-8a604f3796af)
